name: Bandit
on:
  push:
    branches: main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@ab1d87dfccc5a0ffab88be3aaac6ffe35c10d6cd
        with: # optional arguments
          exit_zero: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
